
version: '3'

services:

  postgresql:
    image: postgres
    volumes:
      - db-data2:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: go
      POSTGRES_PASSWORD: admin


volumes:
  db-data2:
